### PR TITLE
The Great Renaming

### PR DESCRIPTION
**Pull request by Kha**
The one proposal I did not implement (yet) is `show ℕ := n` because visually that simply looks like a type mismatch to me :) .

### CODE REVIEW

**Comment by avigad** [comment]
:1st_place_medal: Wow, it looks great. I admire your fortitude.

**Comment by johoelzl** [comment]
NIce! One question regarding `by`: 

Currently `by` is ignored. But shouldn't 
` by t ` translate to ` { t } `. So as an alternative for `solve.`

**Comment by Kha** [comment]
@johoelzl Good catch, fixed

**Comment by leodemoura** [comment]
@kha Great!

BTW, you didn't update `doc/changes.md` ;)

**Comment by avigad** [comment]
BTW, I will make sure TPL has all the information for the next release. So the change log can be brief and refer to that.

**Pull request closed without merging**
