### PR TITLE
fin.succ injective theorem

### PR DESCRIPTION
**Pull request by spl**

### CODE REVIEW

**Comment by spl** [comment]
Hmm. I was waiting on CI to check my code, since I didn't build all of `lean` locally yet, and I didn't expect it to get merged so quickly. 😉 

I think I forgot some implicit variables:

```diff
diff --git a/library/init/data/fin/ops.lean b/library/init/data/fin/ops.lean
index 5d7094a1c..b022849ab 100644
--- a/library/init/data/fin/ops.lean
+++ b/library/init/data/fin/ops.lean
@@ -13,7 +13,7 @@ variable {n : nat}
 protected def succ : fin n → fin (succ n)
 | ⟨a, h⟩ := ⟨nat.succ a, succ_lt_succ h⟩

-protected theorem succ.inj (p : fin.succ a = fin.succ b) : a = b :=
+protected theorem succ.inj {a b : fin n} (p : fin.succ a = fin.succ b) : a = b :=
 by cases a; cases b; exact eq_of_veq (nat.succ.inj (veq_of_eq p))

 def of_nat {n : nat} (a : nat) : fin (succ n) :=
```

(If you're wondering how that could happen, I developed the theorem in a file outside of the `lean` repository and copy-pasted it into `ops.lean`.)

**Comment by spl** [comment]
I'm building the `lean` repository locally now, and there are a lot of errors in the library.

**Comment by digama0** [comment]
Wait, what? I thought this was a mathlib commit. How did I even merge into lean, I don't have push access!

**Comment by digama0** [comment]
Please make another PR fixing the bug or reverting the change. Clearly I was too quick on the trigger here. I would recommend a theorem like this for mathlib, not core lean.

**Comment by spl** [comment]
Apologies for creating a problem. I thought the theorem was appropriate for the core library, given that it was small and adjacent to `fin.succ`. But, I must admit, I don't know the criteria for a submission to the core library. For reference, here's the PR to `mathlib`: https://github.com/leanprover/mathlib/pull/29

**Pull request merged**
