### PR TITLE
Add expression to build with the nix package manager

### PR DESCRIPTION
**Pull request by shlevy**
On top of #1111

### CODE REVIEW

**Comment by gebner** [comment]
FWIW, we have a [lean package in nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/science/logic/lean/default.nix), and you can override it to build current master:

```
nix-build -E 'with import <nixpkgs> {}; lean.override { src = ./.; }'
```

However that doesn't work on the lean3 branch as `src/cmake/Modules/CompBase.cmake` tries to fetch something from github.  In any case, the NINJA_PATH is definitely nicer than the wrapper.

**Comment by shlevy** [comment]
@gebner I prefer building packages without (recent) official releases directly from source checkouts, rather than adding them to nixpkgs and periodically updating them. If this is merged here I'll try to get it working on `lean3` as well :smile:

**Comment by gebner** [comment]
My point was that you can easily use the nixpkgs expression to build a local checkout.  But of course, this only works as long there are no new dependencies or build system changes.

**Comment by soonhokong** [comment]
@gebner,

> However that doesn't work on the lean3 branch as src/cmake/Modules/CompBase.cmake tries to fetch something from github. In any case, the NINJA_PATH is definitely nicer than the wrapper.

There is a workaround. Copy `src/cmake/Modules/cpp14_lang` directory in `master` branch to `lean3` branch. FYI, here is a [link](https://github.com/leanprover/lean/tree/master/src/cmake/Modules/cpp14_lang).

**Comment by leodemoura** [comment]
We are currently working on a new version (branch lean3). It does not depend on ninja anymore.

**Pull request closed without merging**
