### PR TITLE
feat(script/check_md_links.py): make python2/3 compatible

### PR DESCRIPTION
**Pull request by soonhokong**
@Kha, I needed to make some change to run the code with python2. I've checked that it works with both of Python-2.7.11 and Python-3.5.1. Could you check that it looks OK? If so, I'll merge this commit to the blessed repo.

Related link: http://python3porting.com/noconv.html#import-errors

### CODE REVIEW

**Comment by Kha** [comment]
Ah, I didn't check for that. You'll probably want to add a `from __future__ import print_function`, otherwise the output will be mangled.

**Comment by soonhokong** [comment]
@kha, I added it. I also put copyright form.

**Comment by fpvandoorn** [comment]
>  I also put copyright form.

You made a (copy-paste) error with the name in the copyright form.

**Comment by soonhokong** [comment]
@fpvandoorn, oh I made a mistake :-( 
I just fixed it. Thanks for the notice!

**Pull request closed without merging**
