### PR TITLE
Move out lean-mode

### PR DESCRIPTION
**Pull request by Kha**

### CODE REVIEW

**Comment by leodemoura** [comment]
@kha I can already see the lean-mode package.
```
  lean-mode          20170920.755 new        melpa      A major mode for the Lean language
```
There are other packages mentioning lean-mode.
```
  company-lean       20170920.708 new        melpa      A company backend for lean-mode
  helm-lean          20170919.934 new        melpa      Helm interfaces for lean-mode
```
Are they installed automatically?

**Comment by Kha** [comment]
> Are they installed automatically?

No, you should install all three of them to retain the same functionality (well, the latter two imply `lean-mode`). See also the readme of https://github.com/leanprover/lean-mode; after setting up the completion keyboard shortcut, everything should behave as previously.

**Comment by leodemoura** [comment]
@kha I got a bunch of warning messages:
```
Leaving directory `/home/leo/.emacs.d/elpa/seq-2.20'

Compiling file /home/leo/.emacs.d/elpa/seq-2.20/seq-24.el at Thu Oct  5 17:33:52 2017
Entering directory `/home/leo/.emacs.d/elpa/seq-2.20/'

Compiling file /home/leo/.emacs.d/elpa/seq-2.20/seq-25.el at Thu Oct  5 17:33:52 2017
seq-25.el:522:16:Warning: reference to free variable `seq-random-elt'
seq-25.el:525:20:Warning: reference to free variable `sequence'

In end of data:
seq-25.el:531:1:Warning: the following functions are not known to be defined: cl-defgeneric,
    sequence, seq-empty-p, seq-elt, seq-length

Compiling file /home/leo/.emacs.d/elpa/seq-2.20/seq-autoloads.el at Thu Oct  5 17:33:52 2017

Compiling file /home/leo/.emacs.d/elpa/seq-2.20/seq-pkg.el at Thu Oct  5 17:33:52 2017
seq-pkg.el:1:1:Warning: `"sequences"' is a malformed function

Compiling file /home/leo/.emacs.d/elpa/seq-2.20/seq.el at Thu Oct  5 17:33:52 2017
Leaving directory `/home/leo/.emacs.d/elpa/seq-2.20/'

Compiling file /home/leo/.emacs.d/elpa/seq-2.20/tests/seq-tests.el at Thu Oct  5 17:33:52 2017
Entering directory `/home/leo/.emacs.d/elpa/seq-2.20/tests/'

Compiling no file at Thu Oct  5 17:33:53 2017
Leaving directory `/home/leo/.emacs.d/elpa/let-alist-1.0.5'

Compiling file /home/leo/.emacs.d/elpa/let-alist-1.0.5/let-alist-autoloads.el at Thu Oct  5 17:33:53 2017
Entering directory `/home/leo/.emacs.d/elpa/let-alist-1.0.5/'

Compiling file /home/leo/.emacs.d/elpa/let-alist-1.0.5/let-alist-pkg.el at Thu Oct  5 17:33:53 2017
let-alist-pkg.el:1:1:Warning: `"extensions"' is a malformed function

Compiling file /home/leo/.emacs.d/elpa/let-alist-1.0.5/let-alist.el at Thu Oct  5 17:33:53 2017

Compiling no file at Thu Oct  5 17:33:53 2017
Leaving directory `/home/leo/.emacs.d/elpa/flycheck-20170911.127'

Compiling file /home/leo/.emacs.d/elpa/flycheck-20170911.127/flycheck-autoloads.el at Thu Oct  5 17:33:53 2017
Entering directory `/home/leo/.emacs.d/elpa/flycheck-20170911.127/'

Compiling file /home/leo/.emacs.d/elpa/flycheck-20170911.127/flycheck-buttercup.el at Thu Oct  5 17:33:53 2017

Compiling file /home/leo/.emacs.d/elpa/flycheck-20170911.127/flycheck-ert.el at Thu Oct  5 17:33:54 2017

Compiling file /home/leo/.emacs.d/elpa/flycheck-20170911.127/flycheck-pkg.el at Thu Oct  5 17:33:54 2017
flycheck-pkg.el:1:1:Warning: `"convenience"' is a malformed function

Compiling file /home/leo/.emacs.d/elpa/flycheck-20170911.127/flycheck.el at Thu Oct  5 17:33:54 2017

Compiling no file at Thu Oct  5 17:33:55 2017
Leaving directory `/home/leo/.emacs.d/elpa/lean-mode-20170920.755'

Compiling file /home/leo/.emacs.d/elpa/lean-mode-20170920.755/lean-debug.el at Thu Oct  5 17:33:55 2017
Entering directory `/home/leo/.emacs.d/elpa/lean-mode-20170920.755/'

Compiling file /home/leo/.emacs.d/elpa/lean-mode-20170920.755/lean-dev.el at Thu Oct  5 17:33:55 2017

Compiling file /home/leo/.emacs.d/elpa/lean-mode-20170920.755/lean-eri.el at Thu Oct  5 17:33:55 2017
lean-eri.el:9:1:Warning: cl package required at runtime

Compiling file /home/leo/.emacs.d/elpa/lean-mode-20170920.755/lean-flycheck.el at Thu Oct  5 17:33:56 2017

Compiling file /home/leo/.emacs.d/elpa/lean-mode-20170920.755/lean-hole.el at Thu Oct  5 17:33:56 2017

Compiling file /home/leo/.emacs.d/elpa/lean-mode-20170920.755/lean-info.el at Thu Oct  5 17:33:56 2017

Compiling file /home/leo/.emacs.d/elpa/lean-mode-20170920.755/lean-input.el at Thu Oct  5 17:33:56 2017

In lean-input-export-translations:
lean-input.el:1160:33:Warning: `format' called with 1 args to fill 0 format
    field(s)

Compiling file /home/leo/.emacs.d/elpa/lean-mode-20170920.755/lean-leanpkg.el at Thu Oct  5 17:33:56 2017

Compiling file /home/leo/.emacs.d/elpa/lean-mode-20170920.755/lean-message-boxes.el at Thu Oct  5 17:33:56 2017

Compiling file /home/leo/.emacs.d/elpa/lean-mode-20170920.755/lean-mode-autoloads.el at Thu Oct  5 17:33:56 2017

Compiling file /home/leo/.emacs.d/elpa/lean-mode-20170920.755/lean-mode-pkg.el at Thu Oct  5 17:33:56 2017
lean-mode-pkg.el:1:1:Warning: `"languages"' is a malformed function

Compiling file /home/leo/.emacs.d/elpa/lean-mode-20170920.755/lean-mode.el at Thu Oct  5 17:33:56 2017

Compiling file /home/leo/.emacs.d/elpa/lean-mode-20170920.755/lean-right-click.el at Thu Oct  5 17:33:56 2017

Compiling file /home/leo/.emacs.d/elpa/lean-mode-20170920.755/lean-server.el at Thu Oct  5 17:33:56 2017

Compiling file /home/leo/.emacs.d/elpa/lean-mode-20170920.755/lean-settings.el at Thu Oct  5 17:33:56 2017

Compiling file /home/leo/.emacs.d/elpa/lean-mode-20170920.755/lean-syntax.el at Thu Oct  5 17:33:56 2017
lean-syntax.el:63:40:Warning: `mapcar' called for effect; use `mapc' or
    `dolist' instead
lean-syntax.el:70:40:Warning: `mapcar' called for effect; use `mapc' or
    `dolist' instead
lean-syntax.el:79:40:Warning: `mapcar' called for effect; use `mapc' or
    `dolist' instead
lean-syntax.el:107:33:Warning: `mapcar' called for effect; use `mapc' or
    `dolist' instead
lean-syntax.el:108:33:Warning: `mapcar' called for effect; use `mapc' or
    `dolist' instead
lean-syntax.el:109:34:Warning: `mapcar' called for effect; use `mapc' or
    `dolist' instead

Compiling file /home/leo/.emacs.d/elpa/lean-mode-20170920.755/lean-type.el at Thu Oct  5 17:33:56 2017

In end of data:
lean-type.el:107:1:Warning: the function `eldoc-message' is not known to be
    defined.

Compiling file /home/leo/.emacs.d/elpa/lean-mode-20170920.755/lean-util.el at Thu Oct  5 17:33:56 2017
```

**Comment by leodemoura** [comment]
@kha I installed the packages.
The following features are working for me
- Red squiggly lines
- Type information
- Tactic state visualization

But, I'm having the following problems
- Jump to definition. If the buffer `*Lean Goal*` is open, then I get messages like
```
error: interrupted
```
and
```
error: unknown exception
```
in the mini buffer when I try to jump to definition.
If I close the buffer `*Lean Goal*`, then it works as expected.

- Auto completion. I added
```
(global-set-key (kbd "S-SPC") #'company-complete)
```
to my .emacs file, but I'm getting the following error message when I press `S-SPC`.
```
Symbol's function definition is void: company-complete
```

**Comment by jroesch** [comment]
👍

**Comment by leodemoura** [comment]
@jroesch Does it work for you? Can you reproduce the problems I had?

**Comment by Kha** [comment]
@leodemoura Thanks for testing the packages!

> Jump to definition. If the buffer *Lean Goal* is open, then I get messages like

Are you sure this is related to the move? I can reproduce the issue and found the problem (just not a fix, yet), though this should have been broken since January.

> to my .emacs file, but I'm getting the following error message when I press S-SPC.

Mmh, it works for me in a fresh emacs instance. Did you perhaps install `company-lean` only after opening that Lean file? Does the problem persist after restarting emacs, as well as after executing `M-x eval-expr RET (company-lean-hook)`?

**Comment by leodemoura** [comment]
> Are you sure this is related to the move? 

I have no idea. I found it by accident when testing the mode features.

> I can reproduce the issue and found the problem (just not a fix, yet), though this should have been broken since January.

What will be the process to fix lean-mode bugs? We push the commit to the new repo, and then what should we do?

> Mmh, it works for me in a fresh emacs instance. Did you perhaps install company-lean only after opening that Lean file? Does the problem persist after restarting emacs, as well as after executing M-x eval-expr RET (company-lean-hook)?

I restarted several times. The function `company-complete` doesn't even exist on my Emacs.
I will try `M-x eval-expr RET (company-lean-hook)` when I get to the office.

**Comment by Kha** [comment]
> I have no idea. I found it by accident when testing the mode features.

This might also explain the `interrupted` issue @cipher1024 reported on Gitter when trying to open the declaration list. I will open an issue in the new repo.

> What will be the process to fix lean-mode bugs? We push the commit to the new repo, and then what should we do?

MELPA will automatically build and update the package(s) (multiple times a day, I think). Users can then update the packages as described under "Updating Packages" in https://melpa.org/#/getting-started. I can add that information to the readme.

**Comment by leodemoura** [comment]
> MELPA will automatically build and update the package(s) (multiple times a day, I think). Users can then update the packages as described under "Updating Packages" in https://melpa.org/#/getting-started. I can add that information to the readme.

This is good.
What is the process to change something locally and test it? I am assuming it is something like that:
- Uninstall the melpa packages
- git clone the lean-mode repo
- Set .emacs file to use local `lean-mode` repo
- Fix/modify/add and test
- push change to lean-mode repo

**Comment by Kha** [comment]
> What is the process to change something locally and test it?

I'm not sure it is the best workflow, but so far I've been basically doing what you described. I added the following to my init.el:
```
  (add-to-load-path "~/lean/lean-mode/")
  (require 'company-lean)
  (require 'helm-lean)
```
I'll add something like that to the readme.

**Comment by leodemoura** [comment]
@kha I uninstalled the packages and tried to install one by one in the following order:
- `lean-mode`
- `company-lean`
- `helm-lean`

When installing `helm-lean`, I get the error:
```
Package `emacs-24.4' is unavailable
```
The `*Messages*` buffer contains
```
package-compute-transaction: Package `emacs-24.4' is unavailable
```

I'm using Emacs 24.3.50.1

**Comment by leodemoura** [comment]
@kha auto completion seems to work now, and `S-SPC` works as expected.
I suspect `company-lean` was not installed the first time because `helm-lean` failed to be installed.
It seems the real issue is that `helm-lean` depends on Emacs 24.4.

**Comment by leodemoura** [comment]
@kha I will merge this PR. Could you please confirm that `helm-lean` depends on Emacs 24.4, and update the lean-mode README instruction file?

**Pull request closed without merging**
