### PR TITLE
fix(emacs/lean-server): make sure all timers are wrapped in save-match-data

### PR DESCRIPTION
**Pull request by gebner**
@leodemoura Does this fix the issue with `M-/`?

### CODE REVIEW

**Comment by leodemoura** [comment]
@gebner It did not fix it. I am still experiencing the same bug with `M-/` and `query-replace`.

**Comment by gebner** [comment]
Okay, that's bad.  I can't reproduce it under either linux or windows (both emacs 25.1).

**Comment by leodemoura** [comment]
Could you install Emacs 24.5.1?

BTW, Ubuntu 16.04 uses Emacs 24.5.1. I'm experiencing the bug with the default Ubuntu 16.04 installation.

**Comment by gebner** [comment]
Can reproduce with emacs 24.5, I'll try to figure out what goes wrong.

**Comment by gebner** [comment]
@leodemoura I can now call `M-/` in emacs 24 without jumping to the top of the file.

**Comment by leodemoura** [comment]
@gebner Thanks! It works for me too.

**Pull request closed without merging**
