### PR TITLE
Python3 compat fix

### PR DESCRIPTION
**Pull request by favonia**
I put an extra (and wrong) colon in the end.

### CODE REVIEW

**Comment by leodemoura** [comment]
@favonia @soonhokong 
We have another problem: style check does not work if the system does not have `six`. 
The problem is that `cpplint.py` is not in `bin` but `src/cmake/Modules/cpplist.py`.

**Comment by soonhokong** [comment]
@favonia, what would be a good solution for this? What I know is to append "../../../bin/python_lib" to python path using `sys.path.append`. What do you think?

**Comment by soonhokong** [comment]
@favonia, could you check the two commits - e7099ee and 421846e? If you confirm this, I'll push them to the master branch.

**Comment by favonia** [comment]
@soonhokong `unicode` is not valid in Python 3. I thought `cpplint.py` was used in the configuration/compilation so I didn't notice these bugs (including the colon). I'd like to fix these scripts. Could you tell me the usage and the commands you ran to produce these errors?

**Comment by soonhokong** [comment]
@favonia, I see.

> Could you tell me the usage and the commands you ran to produce these errors?

We have a build target `style` which runs `cpplint.py` over `.cpp` and `.h` files. In case you're using `ninja`, you can invoke it via `ninja style`. If you're using GNU make, you can do `make style`.

To simplify the test, you can pass any `cpp`/`.h` file to `cpplint.py` as an argument.

**Comment by favonia** [comment]
This pull request should fix many known problems.  Moreover, we no longer need ``six.py``.

**Comment by favonia** [comment]
This pull request should fix many known problems.  Moreover, we no longer need `six.py`.  However some builds are still failing and I'm still working on them.

**Comment by leodemoura** [comment]
Ok, I will wait.

**Comment by favonia** [comment]
I think it is working.  Please check.

**Comment by leodemoura** [comment]
It works for me. I will merge your changes.

Many thanks,
Leo

**Pull request closed without merging**
