### PR TITLE
chore(library/inductive_compiler/nested.cpp): prove all theorems in C++

### PR DESCRIPTION
**Pull request by dselsam**
Don't call tactics in the inductive compiler so that we can use it when defining `pexpr`.

### CODE REVIEW

**Comment by dselsam** [comment]
hold on, fixing build issue...

**Comment by dselsam** [comment]
Fixing broken test...

**Comment by jroesch** [comment]
👍

**Comment by leodemoura** [comment]
@dselsam It passed all tests. So, I am assuming it is ready to be merged, right?

**Comment by dselsam** [comment]
Yes.

**Pull request closed without merging**
