### PR TITLE
feat(init/meta/interactive): change at tactic

### PR DESCRIPTION
**Pull request by digama0**
addresses #1641

### CODE REVIEW

**Comment by leodemoura** [comment]
@digama0 Could you please add a test file for the new feature?

**Comment by leodemoura** [comment]
Here is an example:
https://github.com/leanprover/lean/blob/92a72b238b062828afe69debe8df3709c3887b6e/tests/lean/run/tactic_ref.lean

**Comment by jroesch** [comment]
If you are going to take the time to modify change, we might as well make change support multiple hypotheses  since the implementation for a single hypothesis is not much different then doing it for all of them. You should just need to revert/re-intro all of them.

**Comment by johoelzl** [comment]
@jroesch can you give me a example to show the syntax? I guess `change T at a b c` does not make much sense. When I want to change more than one hyptothesis, I want to give different new types for these hyptohesis. If there is not a nice syntax it will be hard to document.

**Comment by jroesch** [comment]
@johoelzl I believed our change tactic worked like Coq's but I see that might not actually be the case. It requires that we replace the "entire" goal? you can get away with `change (1 + 2) with 3 in *` in Coq, and it it would replace all occurrences of the subterm.

```
Lemma foo : 1 + 2 = 3 -> 1 + 2 = 3 -> 3 = 1 + 2.
Proof.
  change (1 + 2) with 3 in *.
  reflexivity.
Qed.
```

**Comment by digama0** [comment]
@jroesch I added an implementation of `change A with B` along the lines you describe. `change with` can be used with any location specification, but `change at` can only work on one hypothesis, for exactly the reason @johoelzl says. In principle, we could just change all the hypotheses for the given target, but that has extremely limited practical application. (Another possible extension is to support multiple `change with` in a list, similar to `rw`.)

**Comment by digama0** [comment]
The error reporting could still be improved. For example:

    example (h : 1 + 2 = 3) : true :=
    by change 3 = 4 at h

    tactic.change failed, given type
      3 = 4 → true
    is not definitionally equal to
      1 + 2 = 3 → true
    state:
    ⊢ 1 + 2 = 3 → true

As you can see, the error shows all the reverted hypotheses as well as the actual failed definitional equality. Is the `is_def_eq` predicate exposed to lean?

**Pull request closed without merging**
