### PR TITLE
Add user-defined commands and use them to define `coinductive` in Lean

### PR DESCRIPTION
**Pull request by Kha**
The move itself is of dubious value, but the newly exposed primitives should help with defining other inductive-like commands and of course user-defined commands in general.

### CODE REVIEW

**Comment by Kha** [comment]
We could/should? of course move `coinductive` out of `init` now.

**Comment by leodemoura** [comment]
@kha I will merge this PR after we release 3.2.0

**Comment by Kha** [comment]
@leodemoura Sure, there's no rush. Also reminds me to update the changelog.

**Comment by Kha** [comment]
I didn't actively plan for it, but overriding existing commands seems to work. So one could define just the bare command needed for the basic tactic framework in C++ and then implement the full thing in Lean.

**Pull request closed without merging**
