### PR TITLE
Fix crash on Windows/VS when invoking external processes

### PR DESCRIPTION
**Pull request by nunoplopes**
There was a mismatch on file descriptors vs Handles on Windows.

I've also removed some dead code while at it :)

### CODE REVIEW

**Comment by leodemoura** [comment]
Does this issue also affect MSYS2 and cygwin builds?

**Comment by leodemoura** [comment]
BTW, two tests are failing with this commit:
```
The following tests FAILED:
	 20 - leantest_io_process_echo.lean (Failed)
	473 - leanruntest_io_process_env.lean (Failed)
```
We use `ctest` to run the test suite. 
We can execute the second test using:
```
% bin/lean tests/lean/run/io_process_env.lean 
/home/leo/projects/lean/tests/lean/run/io_process_env.lean:4:0: error: invalid io action, handle has been closed
bar
```

**Comment by nunoplopes** [comment]
gah, I made a typo. Tests fixed now.

**Comment by leodemoura** [comment]
merged

**Pull request closed without merging**
