### PR TITLE
fix(frontends/lean/parser): save noncomputable theory flag in snapshots

### PR DESCRIPTION
**Pull request by gebner**

### CODE REVIEW

**Comment by gebner** [comment]
This is now the second flag that has been missing from the snapshots, and I'm still not sure if we're missing anything else.  I guess I'll refactor the parser so that we just always use snapshots, i.e. parse one command, restore from snapshot, and repeat again.

**Comment by leodemoura** [comment]
> I guess I'll refactor the parser so that we just always use snapshots, i.e. parse one command, restore from snapshot, and repeat again.

I think this change can wait.
We are planning to refactor the parser to support the parser extensions written in Lean.
We can combine both changes in the same refactoring.

**Comment by gebner** [comment]
> We can combine both changes in the same refactoring.

I just saw the design of the parser extensions in your comment at #1340, and I agree, it makes sense to combine the two changes.  AFAICT the parser extension monad will be very similar to the tactic monad, except that we have `parser_state` instead of `tactic_state`.  Once we have proper first-class parser states, we can drop the old snapshot infrastructure.
We can even move the saving of the snapshots out of the parser.  This could be handled by the module_mgr.

But I think in the meantime, we should still merge this PR.  Otherwise files with the `noncomputable theory` flag break if you edit them in the middle.

**Comment by leodemoura** [comment]
> But I think in the meantime, we should still merge this PR. Otherwise files with the noncomputable theory flag break if you edit them in the middle.

I'm planning to merge it. Yesterday was an "intense" day of hacking. I will do it today.

**Pull request closed without merging**
