### PR TITLE
Real numbers

### PR DESCRIPTION
**Pull request by robertylewis**
Pending a bunch of small lemmas about positive nats and rationals: here are the real numbers, up to being a commutative ring. This is done constructively, roughly following Bishop and Bridges.

(Sorry for the messy commit history...)

### CODE REVIEW

**Comment by leodemoura** [comment]
@soonhokong 
I'm having problems integrating this pull request.
The problem is that there are many Merge's, and the rebase is producing many conflicts.
Do you have tricks / "git magic" for handling this kind of issue?

Thanks,
Leo

**Comment by avigad** [comment]
@soonhokong @leodemoura @rlewis1988 

If it is a problem, I don't think it would be too hard for Rob to do a fresh clone of the repository, and then add the new files. I think there are only two files changed in the current library (field and ordered_field), and then everything else is a new addition.

**Comment by robertylewis** [comment]
Yeah, again, I'm sorry for the mess. I had an issue with rebase at one point and had to merge, and didn't realize until now how messy things were.

The only changes should be in the new folder /data/real, algebra/ordered_group and ordered_field, and /data/rat/order. I'm happy to start fresh if that will help.

**Comment by leodemoura** [comment]
> I'm happy to start fresh if that will help.

That would be super helpful, but let's wait for @soonhokong feedback.
Perhaps, he knows some "git magic" for this kind of situation.

**Comment by soonhokong** [comment]
@leodemoura and @rlewis1988, I think it's easier to start fresh, add files, and commit changes. 

There are 7 files changed/added in the pull-request. I would make a commit per directory -- `library/algebra`, `library/data/rat`, `library/data/real`. Of course, please feel free to split into more commits if necessary.

```
library/algebra/ordered_field.lean
library/algebra/ordered_group.lean
library/data/rat/basic.lean
library/data/rat/order.lean
library/data/real/basic.lean
library/data/real/default.lean
library/data/real/real.md
```

**Comment by leodemoura** [comment]
subsumed by #625

**Pull request closed without merging**
