### PR TITLE
Integer floor/ceiling and supremum property for reals

### PR DESCRIPTION
**Pull request by robertylewis**
This proves that every bounded, inhabited set of reals has a supremum. The proof does not use Cauchy completeness, so in effect this is a second completeness proof. (The proof from Cauchy completeness uses most of the same machinery as the direct proof.)

To prove this we use various embedding integers in the reals: we need integer floor and ceiling, and an Archimedean property.

### CODE REVIEW

**Comment by leodemoura** [comment]
@rlewis1988 in the list above, we have the commit `temporary commit: ...`.
I squashed it before integrating your changes.
I also checked if it was still crashing Lean. It does not. I think the bug fixes performed this week fixed the problem.

Best,
Leo

**Comment by robertylewis** [comment]
Oops, sorry! I thought I had removed that commit from master when I made a new branch.

**Comment by robertylewis** [comment]
A question about this commit: in complete.lean line 753, I define

``` lean
theorem rat.pow_add (a : ℚ) (m : ℕ) : ∀ n, rat.pow a (m + n) = rat.pow a m * rat.pow a n :=
  rat.pow_add a m
```

Without this "redefinition," the rewrite using rat.pow_add in the following proof breaks. It remains broken if you try substituting rat.pow_add instead of rewriting. There are no implicit arguments that are being filled in by the redefinition.

I guess, since rat.pow_add is defined by migrate, the definition is "complicated" and Lean doesn't find the useful version without a hint. This is problematic though. Leo, do you know what's going on here? Is there a good way to avoid this?

**Comment by avigad** [comment]
If you print `rat.pow_add` just before redefining it, you will see that it is a mess. I think this is the result of a lack of robustness in the migrate command -- things that are defined in algebra have to be redefine manually before the migrate, or else they get expanded too much. I will try to fix this now.

**Comment by avigad** [comment]
Yup, that was it. It was easy to fix (in pull request #761). Because `field` imports `group_power`, power is was defined for `rat` in `rat.basic`, and we have to define the local version before doing the migrate.

This is an annoying, non-user friendly aspect of `migrate`. I believe Leo is planning to fix this, by making migrate declare local versions of all definitions in the source. But it is tricky. `migrate` should possibly also define notations and transfer attributes, which it doesn't do now. But then if it does, there will probably be situations where the user wants to override that behavior.

**Comment by leodemoura** [comment]
@avigad the `migrate` command uses a simple heuristic to decide what is going to be unfolded: it does not unfold definitions from the namespace we are migrating to. The problem is that `pow_add` is mixing `rat` and `nat`. So, the definitions from `nat` are being expanded when we migrate from `algebra` to `rat`. This is why we see `nat.rec`s when we print `rat.pow_add`.

I'm not happy with this command, we need a better solution. 
Another nasty thing with this command is that we have to enable `migrate.trace` to understand what is going on.

**Comment by avigad** [comment]
Actually, the problem is that we needed to define `rat.pow` explicitly in `rat.basic` before the migrate. I did that now, so we're good. And we're on the same page about `migrate`. 

Getting all the things we want -- handling definitions, handling metadata,  handling parameters, ... will be a real headache for you. But let's not let that obscure the fact that even in its current state, `migrate` is really great.

**Comment by leodemoura** [comment]
> But let's not let that obscure the fact that even in its current state, migrate is really great.

Whenever I use it I get upset :-(
I basically have to turn on `migrate.trace` and then manually inspect the trace messages and check if it did what I wanted it to do.

**Comment by avigad** [comment]
I usually do `print prefix` afterwards, open up the messages window in a new frame, and scroll through to make sure everything looks o.k.

Remember, I used to do migrates /by hand/. Maybe the command isn't robust enough yet for everyday users (and we still haven't described it in the tutorial), but I am very happy we have it.

**Pull request closed without merging**
