### PR TITLE
fix(frontends/lean/parser): support open inside sections with parameters

### PR DESCRIPTION
**Pull request by gebner**
At the moment the following works:
```lean
section
parameter α : Type
inductive foo : Type | a : α → foo | b
check (foo.b : foo)
end
```

But this doesn't:
```lean
open foo
check (b : foo)
```

It feels wrong to interpret the environment's aliases using the parser's local declaration map as done in this PR, but it is to the easiest solution I could think of here.

### CODE REVIEW

**Comment by gebner** [comment]
Please wait with merging for a second, I just noticed that this fix doesn't work if we're inside a namespace.

**Comment by gebner** [comment]
Okay, it works now, but I have no idea whether that's the right way to solve it.

**Comment by gebner** [comment]
A related issue is that parameters are not exposed to the tactics (at least as far as I can tell), not even `to_expr` respects them:
```lean
run_command (do
  e ← to_expr `(b),
  t ← infer_type e,
  trace t)

-- prints: Π (α : Type), foo α
```

**Comment by leodemoura** [comment]
I'm working on this issue.
To fix the `tactic` related issue, I will refactor the `aliases` module. 
We need to store the parser "local_refs" (such as `b` ==> `foo.b  α`) in the environment. Otherwise, the tactic framework will not see them since it does not have access to the `parser`.

**Comment by leodemoura** [comment]
In the commit above, I addressed the original issue by changing how the aliases are created. 
The code will be cleaner after the `aliases` module refactoring since it will also store the entry `b` ==> `foo.b α`

**Comment by Kha** [comment]
Leo, I believe we discussed implementing a more "declarative" version of `open` at some point where instead of replaying commands onto the environment, we derive a (cached) name map from all active `open` commands when needed. I proposed this for fixing the old "have to re-open a namespace after changing it" issue, but I assume it could also simplify this issue?

**Comment by leodemoura** [comment]
The commit above solves the issues above, and cleanup the solution.

**Comment by leodemoura** [comment]
@kha Yes, I remember. We should implement it in the future.
However, the issue raised here is a little bit orthogonal to it. 
In Lean, parameters are simulated. See discussion at https://github.com/leanprover/lean/issues/554

**Comment by leodemoura** [comment]
@gebner Note that the example 
```lean
run_command (do
  e ← to_expr `(b),
  t ← infer_type e,
  trace t)
```
still doesn't work after the commit above. The issue is that it indirectly uses `α` which is not in the local context. However, the following similar example works.
```lean
include α
example : true :=
by do
  e ← to_expr `(b),
  t ← infer_type e,
  trace t,
 triv
```
because the `include` command forces `α` to be in the local context of the `example`.

**Comment by leodemoura** [comment]
@gebner @kha At #554, I tried to summarize the advantages and disadvantages on the approach used to implement parameters in Lean vs the one used in Coq.

**Comment by leodemoura** [comment]
I didn't push the commit above to the main repo yet because it broke a few tests.

**Comment by gebner** [comment]
This solution is much nicer than my quick fix.

> The issue is that it indirectly uses α which is not in the local context.

What is a direct use?  Only parameters that are referenced in the type?

In the following we now have `α` in the local context, but something still goes wrong:
```lean
def ex : foo := begin trace_state, exact b end
```
```
13:23: α : Type
⊢ foo

13:36: invalid type ascription, expression has type
  _root_.foo α_1
but is expected to have type
  foo
state:
α : Type
⊢ foo
```

**Comment by leodemoura** [comment]
> What is a direct use? Only parameters that are referenced in the type?

Yes, for theorems, only parameters referenced in the type are automatically included because we need to compute the precise type of the theorem before we elaborate it.

For definitions, we also include the value, but we ignore tactics. We ignore tactics because the names occurring there are only resolved at tactic execution time.

BTW, I willing to revise these rules. I'm not super happy with the way Lean handles parameters.

**Comment by leodemoura** [comment]
I will fix the issue at 
```lean
def ex : foo := begin trace_state, exact b end
```

**Comment by leodemoura** [comment]
@gebner @kha I think we should revise how parameters are handled in Lean after the POPL tutorial. It is too confusing (for us and for users). The Coq approach is simpler to understand, the only disadvantage is that the `end` section command would be a synchronization point. What do you think?

**Comment by gebner** [comment]
> The Coq approach is simpler to understand, the only disadvantage is that the end section command would be a synchronization point. What do you think?

So we would first add the parameters as constants, parse the section normally, and then add abstractions to the declarations and replay them onto the environment from before the section?

Whether this requires waiting for the proofs depends on how we define what parameters are used by a lemma.  In my opinion, this should not depend on the proof.  And then it doesn't become a synchronization point either.

One issue that you mentioned in #554 is that almost all other environment changes get lost during the replay.  I think we could solve that problem using the modification lists I proposed in #1243: we would just need to add an `abstract_parameters` method to the modification objects.  Then we can reset the modification list at the begin of a section, and replay the abstracted changes at the end.

**Comment by leodemoura** [comment]
> So we would first add the parameters as constants, parse the section normally, and then add abstractions to the declarations and replay them onto the environment from before the section?

Yes.

> Whether this requires waiting for the proofs depends on how we define what parameters are used by a lemma. In my opinion, this should not depend on the proof. And then it doesn't become a synchronization point either.

Yes, we can enforce this. 

> One issue that you mentioned in #554 is that almost all other environment changes get lost during the replay. I think we could solve that problem using the modification lists I proposed in #1243: we would just need to add an abstract_parameters method to the modification objects.

Yes, I agree. Moreover, when #554 was written we didn't have the attribute manager. It also helps.

I think this will be a good change. The current approach is too fragile, and allows the user to do weird stuff (e.g., use the `rename` tactic to rename a parameter). For example, the following example doesn't work because `b` is mapping to `foo.b α`, but `α` is not in the local context anymore after the `rename`.
```
def ex : foo :=
begin
  trace_state,
  rename α β,
  exact b
end
```
In the new approach, the user will not be able to write this.

**Comment by leodemoura** [comment]
The commits above address the issues raised in this PR. 
The solution is not perfect, and we may change how parameters are implemented in Lean in the future as discussed above.

**Pull request closed without merging**
